### ISSUE TITLE
yamltidy touches comment content

### ISSUE THREAD

**Issue by nicksinger** [perlpunk/yamltidy#13]
I'm trying to tidy a [rather huge file](https://github.com/os-autoinst/salt-states-openqa/blob/9872b00d1b5b1ce6ef0750e15a5612efdb295521/monitoring/grafana/alerting-dashboard-GD.yaml.template) containing jinja-template-code. To avoid jinja being interpreted as valid yaml-syntax (e.g. `{`), I tried to use yaml-comments like so:

```YAML
[…]
    panelId: 65105
    title: '{{ generic_host }}: host up alert'
    uid: '{{ (("host_up_alert_" + generic_host ) | sha512)[:40] }}'
#{% endif %}
- folder: Generic
  interval: 1m
[…]
```

after running yamltidy¹ on that file, it results in:

```YAML
[…]
        panelId: 65105
        title: '{{ generic_host }}: host up alert'
        uid: '{{ (("host_up_alert_" + generic_host ) | sha512)[:40] }}'
  #{  % endif %}
  - folder: Generic
    interval: 1m
[…]
```

this is how the diff looks like (sorry, not public yet), note the additional two spaces between `{` and `%` added:
![Image](https://github.com/user-attachments/assets/0faae042-c0e0-435d-b342-74dacb62909b)

¹with the following config: https://github.com/os-autoinst/salt-states-openqa/blob/c453d5556f0cb5839850f4175b8b79bfc1ed0508/.yamltidy

## Expected result:
I think yamltidy should not touch the contents of the comment, so the expected result would rather look like `  #{% endif %}`. @perlpunk already explained to me, that the content of the comment is not to blame but rather libyaml returning the comment as part of a previous (or next?) block. I'm not sure if I fully understood that reasoning and therefore would kindly ask you to create an upstream bug if there is no workaround possible in yamltidy.
